CREATE EXTENSION IF NOT EXISTS adminpack;
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
DROP DATABASE IF EXISTS znmeb;
DROP DATABASE IF EXISTS voter_reg;
DROP DATABASE IF EXISTS geocoder;
DROP ROLE IF EXISTS znmeb;
CREATE ROLE znmeb 
  WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION; 
CREATE DATABASE znmeb
  WITH OWNER znmeb;
CREATE DATABASE voter_reg
  WITH OWNER znmeb;
CREATE DATABASE geocoder
  WITH OWNER postgres
