CREATE EXTENSION IF NOT EXISTS adminpack;
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
DROP DATABASE IF EXISTS znmeb;
DROP DATABASE IF EXISTS voter_reg;
DROP DATABASE IF EXISTS geocoder;
DROP DATABASE IF EXISTS state;
DROP DATABASE IF EXISTS cd;
DROP DATABASE IF EXISTS county;
DROP DATABASE IF EXISTS zcta5;
DROP DATABASE IF EXISTS elsd;
DROP DATABASE IF EXISTS scsd;
DROP DATABASE IF EXISTS sldl;
DROP DATABASE IF EXISTS sldu;
DROP DATABASE IF EXISTS unsd;
DROP ROLE IF EXISTS znmeb;

CREATE ROLE znmeb 
  WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;
\password znmeb

CREATE DATABASE znmeb
  WITH OWNER znmeb;
\connect znmeb
\i create-postgis-extensions.sql
